Stop using get_primary_monitor()
It doesn't work in Wayland and it is apparently deprecated.

Use get_monitor(0) instead.

Fixes the following error:

Traceback (most recent call last):
  File "/tmp/./cropgtk.py", line 223, in <module>
    wa = display.get_primary_monitor().get_workarea()
AttributeError: 'NoneType' object has no attribute 'get_workarea'

Fixes https://github.com/jepler/cropgui/issues/93.